define: DUK_USE_ARRAY_FASTPATH
introduced: 1.5.0
default: false
tags:
  - performance
  - fastpath
  - lowmemory
description: >
  Enable fast path for Array.prototype operations like push(), pop(), etc.
  The fast path handles dense Array instances which are more common than
  sparse arrays or non-array objects (which Array.prototype operations must
  also support).
